name: bundler
on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]
    
jobs:
  mixer:
    runs-on: ubuntu-latest
    container: 
      image: clearlinux:latest
      options: --privileged --cap-add=SYS_ADMIN
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: clearfraction/mass-rebuild-v2
          workflow: mass-rebuild.yml
          check_artifacts: true
          path: /home
      - name: Build new release
        shell: bash
        run: |
          swupd bundle-add curl --quiet
          cd /home && curl -s -LO https://github.com/clearfraction/bundles/raw/master/build.sh && chmod +x build.sh
          sed -i "s|/V3/usr|/V3/notfound|g" build.sh
          ./build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_USER: paulcarroty
      
  docker:
    needs: mixer
    runs-on: ubuntu-latest
    steps:
      - run: curl -LO https://raw.githubusercontent.com/clearfraction/bundles/master/Dockerfile
      - name: CD
        env:
          APP: "clearfraction"
          VERCEL_REBUILD_HOOK: ${{ secrets.VERCEL_REBUILD_HOOK2 }}
        run: |
          curl -X POST ${VERCEL_REBUILD_HOOK2}
