name: format_bump
on:
  #schedule:
  #  - cron: "0 22 * * 3"
  workflow_dispatch:
    
jobs:
  mixer:
    runs-on: ubuntu-latest
    container: 
      image: clearlinux:latest
      volumes:
        - /opt:/opt
      options: --privileged --cap-add=SYS_ADMIN
    steps:
      - name: Build new release
        shell: bash
        run: |
          rm -rf /opt/*
          swupd bundle-add curl --quiet
          cd /home && curl -s -LO https://raw.githubusercontent.com/clearfraction/bundles/master/format_bump.sh && chmod +x format_bump.sh
          sed -i "s|clearfraction.vercel.app|v2clearfraction.vercel.app|g" format_bump.sh
          sed -i "s|/V3/usr|/V3/notfound|g" format_bump.sh
          sed -i "s|clearfraction/bundles/releases|clearfraction/mass-rebuild-v2/releases|g" format_bump.sh
          sed -i "s|cd /home|cd /home; git remote remove origin; git remote add origin https://github.com/clearfraction/mass-rebuild-v2.git|g" format_bump.sh
          ./format_bump.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: paulcarroty
          APP: "clearfraction"
          VERCEL_REBUILD_HOOK: ${{ secrets.VERCEL_REBUILD_HOOK2 }}
