name: format_bump
on:
  schedule:
    - cron: "0 22 * * 3"
  workflow_dispatch:
  repository_dispatch:
    types: [build]
    
jobs:
  mixer:
    runs-on: ubuntu-latest
    container: 
      image: clearlinux:latest
      options: --privileged --cap-add=SYS_ADMIN
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: clearfraction/mass-rebuild-v2
          workflow: mass-rebuild.yml
          check_artifacts: true
          path: /home
      - name: Build new release
        shell: bash
        run: |
          swupd bundle-add curl --quiet
          cd /home && curl -s -LO https://raw.githubusercontent.com/clearfraction/bundles/master/format_bump.sh && chmod +x format_bump.sh
          sed -i "s|/V3/usr|/V3/notfound|g" build.sh
          sed -i "s|clearfraction/bundles/releases|clearfraction/mass-rebuild-v2/releases|g" build.sh
          sed -i "s|cd /home|cd /home; git remote remove origin; git remote add origin https://github.com/clearfraction/mass-rebuild-v2.git|g" build.sh
          ./format_bump.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: paulcarroty
          APP: "clearfraction"
          VERCEL_REBUILD_HOOK: ${{ secrets.VERCEL_REBUILD_HOOK2 }}
